// This file has been MANUALLY CREATED by merging the code from `main.go`
// and the generated code from `state_string.go` together.
//
// This files has been created for easy use in the play command during present
// THIS IS NOT REQUIRED FOR NORMAL USE

// This file is in it's own folder because that is a requirement for
// go generate to work.
package main

import (
	"fmt"
	"strconv"
)

// BEGIN OMIT
//go:generate stringer -type=State // HL
type State int

const (
	Created State = iota
	Starting
	Started
	Done
)

func main() {
	fmt.Println(Created, Starting, Started, Done)
}

// END OMIT

// Code generated by "stringer -type=State"; DO NOT EDIT.

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Created-0]
	_ = x[Starting-1]
	_ = x[Started-2]
	_ = x[Done-3]
}

const _State_name = "CreatedStartingStartedDone"

var _State_index = [...]uint8{0, 7, 15, 22, 26}

func (i State) String() string {
	if i < 0 || i >= State(len(_State_index)-1) {
		return "State(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}
